sudo: require
dist: xenial
language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_5e8fc27d13ec_key -iv $encrypted_5e8fc27d13ec_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_5e8fc27d13ec_key -iv $encrypted_5e8fc27d13ec_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- sudo apt-get -qq update
- sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra
  texlive-fonts-extra
script:
- "./resume $arguments"
addons:
  ssh_known_hosts: login.ccs.neu.edu
