#!/usr/bin/env bash

phoneNumber=$1

areaCode=${phoneNumber:0:3}
townCode=${phoneNumber:3:3}
number=${phoneNumber:(-4)}

email=$2

host=${email%@*}
domain=${email#*@}

print='\\myprintheader{'$areaCode'}{'$townCode'}{'$number'}{'$host'}{'$domain'}'
web='\\mywebheader'
str="% here"

mkdir print
cp JackFrysinger.tex print/JackFrysinger.tex
cd print

sed -i_bak -e "s/$str/$print/" JackFrysinger.tex
pdflatex JackFrysinger.tex > /dev/null
cp JackFrysinger.pdf ../JackFrysinger-print.pdf

cd ..
rm -rf print

mkdir web
cp JackFrysinger.tex web/JackFrysinger.tex
cd web
sed -i_bak -e "s/$str/$web/" JackFrysinger.tex
pdflatex JackFrysinger.tex > /dev/null
cp JackFrysinger.pdf ../JackFrysinger-web.pdf

cd ..
rm -rf web
